
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy
  failurePolicy: Fail
  name: mclusteradmissionpolicy.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradmissionpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policies-kubewarden-io-v1alpha2-policyserver
  failurePolicy: Fail
  name: mpolicyserver.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - policyservers
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy
  failurePolicy: Fail
  name: vclusteradmissionpolicy.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradmissionpolicies
  sideEffects: None
