
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - policies.kubewarden.io
  resources:
  - clusteradmissionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policies.kubewarden.io
  resources:
  - clusteradmissionpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - policies.kubewarden.io
  resources:
  - clusteradmissionpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policies.kubewarden.io
  resources:
  - policyservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policies.kubewarden.io
  resources:
  - policyservers/finalizers
  verbs:
  - update
- apiGroups:
  - policies.kubewarden.io
  resources:
  - policyservers/status
  verbs:
  - get
  - patch
  - update
