name: kubewarden-controller release
on:
  push:
    tags:
    - 'v*'
jobs:
  ci:
    uses: kubewarden/kubewarden-controller/.github/workflows/ci.yml@main
  release:
    permissions:
      id-token: write
      contents: write
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Install the bom command
        shell: bash
        run: go install sigs.k8s.io/bom/cmd/bom@v0.2.2

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SBOM file
        shell: bash
        run: |
          bom generate -n https://kubewarden.io/kubewarden.spdx -o kubewarden-controller.spdx .

      - name: Sign BOM file
        run: |
          cosign sign-blob --output-certificate kubewarden-controller.spdx.cert \
            --output-signature kubewarden-controller.spdx.sig \
            kubewarden-controller.spdx
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release kubewarden-controller ${{ GITHUB_REF_NAME }}
          draft: false
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
          files: |
            kubewarden-controller.spdx
            kubewarden-controller.spdx.cert
            kubewarden-controller.spdx.sig
