name: kubewarden-controller release
on:
  push:
    tags:
    - 'v*'
jobs:
  ci:
    uses: kubewarden/kubewarden-controller/.github/workflows/ci.yml@main
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Install the bom command
        shell: bash
        run: go install sigs.k8s.io/bom/cmd/bom@v0.2.2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SBOM file
        shell: bash
        run: |
          bom generate -n https://kubewarden.io/kubewarden.spdx -o kubewarden-controller.spdx .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release kubewarden-controller ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}

      - name: Upload SBOM file as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kubewarden-controller.spdx
          asset_name: kubewarden-controller-sbom.spdx
          asset_content_type: text/spdx
